### ISSUE TITLE
.pdf extension is repeated

### ISSUE THREAD

**Issue by yasinaydin** [hkulekci/htmlpdf.net#1]
When I download the file, it saves as `document.pdf.pdf`. I think it should be saved as `document.pdf`
I wanted to fix it but couldn't find where to fix it.

**Comment by hkulekci** [comment]
hey yasin, thank you for your feedback. I sent an update for this. Please check it. 👍

**Comment by yasinaydin** [comment]
Thanks. It looks fixed now :)
